version: '2'
services:
    go:
        image: golang:1.10-alpine
        ports:
            - "4000:8080"
        build: .
        links:
            - postgres
            - redis
        environment:
            DEBUG: 'true'
            PORT: '5432'

    postgres:
        image: postgres:9.5-alpine
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: recipeapi
            POSTGRES_PASSWORD: recipeapi
            POSTGRES_DB: recipeapi
        volumes:
            - ./etc:/something
        command: |
            psql -d $POSTGRES_DB -U $POSTGRES_USER -W $POSTGRES_PASSWORD < /something/setup.sql
    
    redis:
        image: redis:latest

